mysite/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path("<str:name>", views.greet, name="greet"),
    path("dayanand", views.dayanand, name='dayanand')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello.urls")),
    path("tasks/", include("tasks.urls")),
    path("newyear/", include("newyear.urls"))
]

mysite/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name='index')
]

mysite/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name='index'),
    path("add", views.add, name="add")
]

mysite/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    #return HttpResponse("Hello, World!")
    return render(request, "hello/index.html")

def dayanand(request):
    return HttpResponse("Hello Dayanand!")

def greet(request, name):
    #return HttpResponse(f"Hello {name.capitalize()}!")
    return render(request, "hello/greet.html",{
        'name':name.capitalize()
    })

mysite/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html",{
        'newyear':now.month==1 and now.day==1
    })

mysite/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Create your views here.
#tasks = []

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
#    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

def index(request):
    if "tasks" not in request.session:
        request.session['tasks']=[]
    return render(request, "tasks/index.html",{
        "tasks":request.session['tasks']
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            request.session['tasks'] += [task]
#            tasks.append(task)
            return HttpResponseRedirect(reverse('tasks:index'))
        else:
            render(request, "tasks/add.html",{
                "form":form
            })
    return render(request, "tasks/add.html",{
    "form": NewTaskForm()
    })

mysite/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello!</title>
  </head>
  <body>
    <h1>Hello {{ name }}</h1>
  </body>
</html>

mysite/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello!</title>
  </head>
  <body>
    <h1> Hello World!</h1>
  </body>
</html>

mysite/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Is is New Year?</title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
  </head>
  <body>
    {% if newyear %}
      <h1>YES</h1>
    {% else %}
      <h1>NO</h1>
    {% endif %}
  </body>
</html>

mysite/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}
{% block body %}
  <h1>Add Task</h1>
  <form action="{% url 'tasks:add' %}" method="POST">
    {% csrf_token %}
    <!-- <input type="text" name="task"> -->
    {{ form }}
    <input type="submit" >
  </form>
  <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

mysite/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
{% block body %}
  <h1>Tasks</h1>
  <ul>
    {% for task in tasks %}
      <li>{{ task }}</li>
    {% empty %}
      <li>No Tasks</li>
    {% endfor %}
  </ul>
  <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

mysite/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tasks</title>
  </head>
  <body>
    {% block body %}

    {% endblock %}
  </body>
</html>